
const dataTable = [
    {
        id: 1,
        nombreElement: 'Hidrogeno',
        simbolo: 'H',
        descripcion: `El hidrógeno es el elemento químico más ligero y abundante en el universo. Su átomo está formado por un protón y un electrón, y se representa con el símbolo H.`

    },
    {
        id: 2,
        nombreElement: 'Helio',
        simbolo: 'He',
        descripcion: `El helio es un elemento químico de número atómico 2, símbolo He y peso atómico estándar de 4,002602. Es el segundo elemento más ligero y el segundo más abundante en el universo observable, constituyendo el 24 % de la masa de los elementos presentes en nuestra galaxia.`,
    },
    {
        id: 3,
        nombreElement: 'Litio',
        simbolo: 'Li',
        descripcion: `El litio, un elemento químico de símbolo Li, número atómico 3 y masa atómica 6,938, se encuentra en el grupo 1A de la tabla periódica, entre los metales alcalinos. En su forma pura, es un metal blando, blanco plateado y extremadamente ligero, siendo el metal más ligero de todos.`,
    },
    {
        id: 4,
        nombreElement: 'Berilio',
        simbolo: 'Be',
        descripcion: `El berilio, un elemento químico de símbolo Be y número atómico 4, es un metal ligero, duro, grisáceo y quebradizo. Se encuentra en la corteza terrestre en forma de minerales como el berilo y la bertrandita.`,
    },
    {
        id: 5,
        nombreElement: 'Boro',
        simbolo: 'B',
        descripcion: `El boro (símbolo B y número atómico 5) es un elemento químico que no es metálico (aunque a veces se clasifica como metalloide) y se encuentra naturalmente en la corteza terrestre formando parte de minerales boratos.`,
    },
    {
        id: 6,
        nombreElement: 'Carbono',
        simbolo: 'C',
        descripcion: `El carbono, representado por el símbolo C y con número atómico 6, es un elemento químico no metálico que se encuentra en la naturaleza en diversas formas, desde el carbón puro (grafito y diamante) hasta compuestos orgánicos como las proteínas, los carbohidratos y las grasas.`,
    },
    {
        id: 7,
        nombreElement: 'Nitrogeno',
        simbolo: 'N',
        descripcion: `El nitrógeno, representado por el símbolo N y con número atómico 7, es un elemento químico no metálico que compone aproximadamente el 78% de la atmósfera terrestre. Es un gas inodoro, insípido e incoloro que juega un papel fundamental en la vida en la Tierra.`,
    },
    {
        id: 8,
        nombreElement: 'Oxigeno',
        simbolo: 'O',
        descripcion: `El oxígeno, representado por el símbolo O y con número atómico 8, es un elemento químico no metálico, inodoro, insípido e incoloro, que constituye aproximadamente el 21% de la atmósfera terrestre. Es esencial para la respiración de la mayoría de los organismos vivos y juega un papel fundamental en muchos procesos químicos en la naturaleza.`,
    },
    {
        id: 8,
        nombreElement: 'Flúor',
        simbolo: 'F',
        descripcion: `El flúor, representado por el símbolo F y con número atónico 9, es un elemento químico no metálico que se encuentra en la naturaleza como gas de color amarillo pálido.  Juega un papel importante en la salud dental y se agrega a muchos productos dentales.`,
    },
    {
        id: 9,
        nombreElement: 'Neón',
        simbolo: 'Ne',
        descripcion: `Neon, representado por el símbolo Ne y número atómico 10, es un elemento químico noble inodoro, incoloro e inerte que se encuentra naturalmente como gas en la atmósfera terrestre. Pero, a diferencia de su apariencia natural, el neón es famoso por su brillante iluminación cuando se utiliza en lámparas de neón.`,
    },
    {
        id: 10,
        nombreElement: 'Sodio',
        simbolo: 'Na',
        descripcion: `El sodio, representado por el símbolo Na y con número atómico 11, es un elemento químico metálico alcalino de color plateado brillante, blando y altamente reactivo. Es uno de los elementos más abundantes en la corteza terrestre y se encuentra principalmente en forma de cloruro de sodio (sal común).`,
    },
    {
        id: 11,
        nombreElement: 'Magnesio',
        simbolo: 'Mg',
        descripcion: `El magnesio, representado por el símbolo Mg y con número atómico 12, es un elemento químico metálico alcalinotérreo de color blanco plateado, ligero y maleable. Es el octavo elemento más abundante en la corteza terrestre y se encuentra principalmente en minerales como la magnesita y la dolomita.        `,
    },
    {
        id: 12,
        nombreElement: 'Aluminio',
        simbolo: 'Al',
        descripcion: `El aluminio, representado por el símbolo Al y con número atómico 13, es un elemento químico metálico de color blanco plateado, ligero, maleable y dúctil. Es el tercer elemento más abundante en la corteza terrestre y se encuentra principalmente en forma de minerales como la bauxita.`,
    },
    {
        id: 13,
        nombreElement: 'Silicio',
        simbolo: 'Si',
        descripcion: `El silicio, representado por el símbolo Si y con número atómico 14, es un elemento químico metaloide de color grisáceo, cristalino, duro y semiconductor. Es el segundo elemento más abundante en la corteza terrestre, después del oxígeno, y se encuentra principalmente en forma de sílice (SiO2), el componente principal de la arena, el cuarzo y otros minerales.`,
    },
    {
        id: 14,
        nombreElement: 'Fósforo',
        simbolo: 'P',
        descripcion: `El fósforo, representado por el símbolo P y con número atómico 15, es un elemento químico no metálico de color blanco o amarillo pálido, altamente reactivo y esencial para la vida. Se encuentra principalmente en forma de fosfatos en los minerales de la corteza terrestre y en los organismos vivos.`,
    },
    {
        id: 15,
        nombreElement: 'Azufre',
        simbolo: 'S',
        descripcion: `El azufre, representado por el símbolo S y con número atómico 16, es un elemento químico no metálico de color amarillo brillante, con un olor fuerte y característico. Se encuentra principalmente en forma de minerales como la pirita (FeS2), la calcopirita (CuFeS2) y la galena (PbS).`,
    },
    {
        id: 16,
        nombreElement: 'Cloro',
        simbolo: 'Cl',
        descripcion: `El cloro, representado por el símbolo Cl y con número atómico 17, es un elemento químico no metálico de color verde amarillento, gaseoso a temperatura ambiente y con un olor fuerte e irritante. Es uno de los elementos más abundantes en la corteza terrestre y se encuentra principalmente en forma de cloruro de sodio (sal común).`,
    },
    {
        id: 17,
        nombreElement: 'Argón',
        simbolo: 'Ar',
        descripcion: `El argón, representado por el símbolo Ar y con número atómico 18, es un elemento químico gas noble inodoro, incoloro e inerte. Es el tercer gas más abundante en la atmósfera terrestre, constituyendo aproximadamente el 0,934% de su volumen. Se encuentra principalmente en estado gaseoso y no forma compuestos químicos fácilmente debido a su configuración electrónica estable.`,
    },
    {
        id: 18,
        nombreElement: 'Potasio',
        simbolo: 'K',
        descripcion: `El potasio, representado por el símbolo K y con número atómico 19, es un elemento químico metálico alcalino de color blanco plateado, blando y maleable. Se encuentra principalmente en forma de sales minerales en el agua de mar, en los depósitos salinos y en algunos minerales como la carnalita (KCl·MgCl2·6H2O) y la silvita (KCl).`,
    },
    {
        id: 19,
        nombreElement: 'Calcio',
        simbolo: 'Ca',
        descripcion: `El calcio, representado por el símbolo Ca y con número atómico 20, es un elemento químico metálico alcalino térreo de color blanco plateado, maleable y dúctil. Es el mineral más abundante en el cuerpo humano, representando aproximadamente el 1,5-2% del peso corporal total. Se encuentra principalmente en los huesos y dientes, pero también está presente en la sangre, los músculos y otros tejidos.`,
    },
    {
        id: 20,
        nombreElement: 'Escandio',
        simbolo: 'Sc',
        descripcion: `El escandio es un elemento químico de símbolo Sc y número atómico 21. Es un metal de transición de bloque d de color blanco plateado, ligero y que se encuentra en algunos minerales raros. Su nombre proviene de la palabra griega "Skandan", que significa "escalador". El escandio fue descubierto en 1879 por Lars Fredrik Nilson, un químico sueco.`,
    },
    {
        id: 21,
        nombreElement: 'Titanio',
        simbolo: 'Ti',
        descripcion: `El titanio es un elemento químico de símbolo Ti y número atómico 22. Es un metal de transición de bloque d de color gris plateado, ligero y fuerte. Se encuentra en algunos minerales raros.`,
    },
    {
        id: 22,
        nombreElement: 'Vanadio',
        simbolo: 'V',
        descripcion: `El vanadio es un elemento químico con el símbolo V y el número atómico 23. Es un metal de transición de bloque d de color gris plateado, dúctil y maleable. Se encuentra en algunos minerales raros, como la vanadita y la patronita.`,
    },
    {
        id: 23,
        nombreElement: 'Cromo',
        simbolo: 'Cr',
        descripcion: `El cromo es un elemento químico con el símbolo Cr y número atómico 24. Es un metal de transición de bloque d de color gris plateado, duro, brillante y resistente a la corrosión. Se encuentra en algunos minerales, como la cromita y la crocoíta.`,
    },
    {
        id: 24,
        nombreElement: 'Manganeso',
        simbolo: 'Mn',
        descripcion: `El manganeso es un elemento químico con el símbolo Mn y número atómico 25. Es un metal de transición de bloque d de color gris plateado, duro, maleable y dúctil. Se encuentra en algunos minerales, como la pirolusita y la rodocrosita.`,
    },
    {
        id: 25,
        nombreElement: 'Hierro',
        simbolo: 'Fe',
        descripcion: `El hierro (Fe) es un elemento químico de número atómico 26 y símbolo Fe. Es un metal de transición de bloque d de color gris plateado, maleable, dúctil y magnético. Se encuentra en algunos minerales, como la hematita y la magnetita.`,
    },
    {
        id: 26,
        nombreElement: 'Cobalto',
        simbolo: 'Co',
        descripcion: `El cobalto (Co) es un elemento químico con número atómico 27 y símbolo Co. Es un metal de transición de bloque d de color gris plateado, duro, brillante y magnético. Se encuentra en algunos minerales, como la cobaltita y la eritrosina.`,
    },
    {
        id: 27,
        nombreElement: 'Niquel',
        simbolo: 'Ni',
        descripcion: `El níquel es un elemento químico con el símbolo Ni y el número atómico 28. Es un metal de transición blanco plateado, maleable, dúctil y brillante. Se encuentra en algunos minerales, como la pentlandita y la millerita.`,
    },
    {
        id: 28,
        nombreElement: 'Cobre',
        simbolo: 'Cu',
        descripcion: `El cobre es un elemento químico con el símbolo Cu y el número atómico 29. Es un metal de transición de bloque d de color rojo anaranjado, maleable, dúctil y brillante. Se encuentra en algunos minerales, como la calcopirita y la malaquita.`,
    },
    {
        id: 29,
        nombreElement: 'Cinc',
        simbolo: 'Zn',
        descripcion: `El zinc (Zn) es un elemento químico con número atómico 30 y símbolo Zn. Es un metal de transición de bloque d de color gris plateado, brillante, dúctil y maleable. Se encuentra en algunos minerales, como la esfalerita y la smithsonita.`,
    },
    {
        id: 30,
        nombreElement: 'Galio',
        simbolo: 'Ga',
        descripcion: `El galio es un elemento químico con el símbolo Ga y el número atómico 31. Es un metal de transición de bloque d de color gris plateado, blando, maleable y dúctil. Se encuentra en algunos minerales, como la bauxita y la germanita.`,
    },
    {
        id: 31,
        nombreElement: 'Germanio',
        simbolo: 'Ge',
        descripcion: `El germanio (Ge) es un elemento químico con número atómico 32 y símbolo Ge. Es un metaloide de bloque p de color gris plateado, brillante, duro y quebradizo. Se encuentra en algunos minerales, como la germanita y la argirodita.`,
    },
    {
        id: 32,
        nombreElement: 'Arsénico',
        simbolo: 'As',
        descripcion: `El arsénico (As) es un elemento químico con número atómico 33 y símbolo As. Es un semimetal de color gris plateado, brillante y quebradizo. Se encuentra en algunos minerales, como la oropímenta y la realgarita.`,
    },
    {
        id: 33,
        nombreElement: 'Selenio',
        simbolo: 'Se',
        descripcion: `El selenio (Se) es un elemento químico con número atómico 34 y símbolo Se. Es un no metal de bloque p de color gris plateado, brillante y frágil. Se encuentra en algunos minerales, como la calaverita y la esfalerita.`,
    },
    {
        id: 34,
        nombreElement: 'Bromo',
        simbolo: 'Br',
        descripcion: `El bromo (Br) es un elemento químico no metálico con número atómico 35 y símbolo Br. Es un líquido rojo parduzco a temperatura ambiente, el único no metal líquido a dicha temperatura; es volátil y desprende vapores rojizos de olor fuerte y desagradable.`,
    },
    {
        id: 35,
        nombreElement: 'Criptón',
        simbolo: 'Kr',
        descripcion: `El criptón (Kr) es un elemento químico incoloro, inodoro e insípido de la tabla periódica con el símbolo Kr y el número atómico 36. Es un gas noble y es el tercer elemento más abundante en la atmósfera terrestre, después del nitrógeno y el oxígeno. El criptón se encuentra en pequeñas cantidades en el aire, así como en algunos minerales.`,
    },
    {
        id: 36,
        nombreElement: 'Rubidio',
        simbolo: 'Rb',
        descripcion: `El rubidio es un elemento químico con el símbolo Rb y el número atómico 37. Es un metal blando de color blanco plateado, altamente reactivo y pertenece al grupo de los metales alcalinos. El rubidio se encuentra en la naturaleza combinado con otros elementos, como en minerales como la lepidolita y la rubicita. También se encuentra en el agua de mar, aunque en cantidades muy pequeñas.`,
    },
    {
        id: 37,
        nombreElement: 'Estroncio',
        simbolo: 'Sr',
        descripcion: `El estroncio es un elemento químico con el símbolo Sr y el número atómico 38. Es un metal blando de color plateado brillante, algo maleable, también alcalino térreo, que rápidamente se oxida en presencia de aire adquiriendo un tono amarillento por la formación de óxido, por lo que debe conservarse sumergido en parafina.`,
    },
    {
        id: 38,
        nombreElement: 'Itrio',
        simbolo: 'Y',
        descripcion: `El itrio es un elemento químico con el símbolo Y y el número atómico 39. Es un metal de transición plateado brillante, relativamente estable en el aire y químicamente similar a los lantánidos. Las virutas del metal pueden encenderse en el aire cuando exceden los 400 °C.`,
    },
    {
        id: 39,
        nombreElement: 'Circonio',
        simbolo: 'Zr',
        descripcion: `El circonio es un elemento químico con el símbolo Zr y el número atómico 40. Es un metal de transición blanco plateado, duro, resistente a la corrosión y de apariencia similar al acero.`,
    },
    {
        id: 40,
        nombreElement: 'Niobio',
        simbolo: 'Nb',
        descripcion: `El niobio es un elemento químico con el símbolo Nb y el número atómico 41. Es un metal de transición dúctil, gris, blando y poco abundante. Se encuentra en el mineral niobita, también llamado columbita, y se utiliza en aleaciones.`,
    },
    {
        id: 41,
        nombreElement: 'Molibdeno',
        simbolo: 'Mo',
        descripcion: `El molibdeno es un elemento químico con el símbolo Mo y el número atómico 42. Es un metal de transición blanco plateado, duro, denso y refractario que se encuentra en varios minerales. El molibdeno es un elemento esencial para algunos organismos y se utiliza en una variedad de aplicaciones industriales.`,
    },
    {
        id: 42,
        nombreElement: 'Tecnecio',
        simbolo: 'Tc',
        descripcion: `El tecnecio es un elemento químico con el símbolo Tc y el número atómico 43. Es el primer elemento producido artificialmente y el único elemento de la tabla periódica que no tiene isótopos estables. El tecnecio es un metal radiactivo de transición de color gris plateado que se encuentra en los productos de fisión nuclear.`,
    },
    {
        id: 43,
        nombreElement: 'Rutenio',
        simbolo: 'Ru',
        descripcion: `El rutenio es un elemento químico con el símbolo Ru y el número atómico 44. Es un metal de transición raro, duro, quebradizo y de color blanco grisáceo que pertenece al grupo del platino. Se encuentra normalmente en minas de platino y se emplea como catalizador en algunas aleaciones de platino.`,
    },
    {
        id: 44,
        nombreElement: 'Rodio',
        simbolo: 'Rh',
        descripcion: `El rodio es un elemento químico con el símbolo Rh y el número atómico 45. Es un metal de transición raro, duro, blanco plateado y brillante que se encuentra normalmente en minas de platino. Es uno de los elementos más raros de la corteza terrestre.`,
    },
    {
        id: 45,
        nombreElement: 'Paladio',
        simbolo: 'Pd',
        descripcion: `El paladio es un elemento químico con el símbolo Pd y el número atómico 46. Es un metal de transición blanco plateado, blando, dúctil y maleable que se encuentra en el grupo del platino.`,
    },
    {
        id: 46,
        nombreElement: 'Plata',
        simbolo: 'Ag',
        descripcion: `La plata es un elemento químico con el símbolo Ag y el número atómico 47. Es un metal de transición blanco brillante, blando, dúctil y maleable. Es el metal más conductor de calor y electricidad de todos los elementos. La plata también es muy reflectante y tiene la mayor conductividad térmica y eléctrica de todos los metales.`,
    },
    {
        id: 47,
        nombreElement: 'Cadmio',
        simbolo: 'Cd',
        descripcion: `El cadmio (Cd) es un elemento químico con el número atómico 48 y símbolo Cd. Es un metal de transición pesado, blando, blanco azulado y relativamente poco abundante, siendo uno de los metales más tóxicos.`,
    },
    {
        id: 48,
        nombreElement: 'Indio',
        simbolo: 'In',
        descripcion: `El indio es un elemento químico con el símbolo In y el número atómico 49. Es un metal de transición blanco plateado, blando, dúctil y maleable que se encuentra en el grupo del boro. Se encuentra en la corteza terrestre como mineral de indio y se obtiene como subproducto del procesamiento de minerales de zinc, plomo, estaño y cobre.`,
    },
    {
        id: 49,
        nombreElement: 'Estaño',
        simbolo: 'Sn',
        descripcion: `El estaño es un elemento químico con el símbolo Sn y el número atómico 50. Es un metal blanco plateado, maleable y dúctil que se encuentra en el grupo del carbono. Se encuentra en la corteza terrestre como mineral de casiterita y se obtiene como subproducto del procesamiento de minerales de tungsteno, wolframio y niobio.`,
    },
    {
        id: 50,
        nombreElement: 'Antimonio',
        simbolo: 'Sb',
        descripcion: `El antimonio es un elemento químico con el símbolo Sb y el número atómico 51. Es un metaloide blanco plateado, quebradizo y con un brillo bajo que se encuentra en el grupo 15 de la tabla periódica. Es uno de los elementos más raros de la corteza terrestre.`,
    },
    {
        id: 51,
        nombreElement: 'Telurio',
        simbolo: 'Te',
        descripcion: `El telurio es un elemento químico con el símbolo Te y el número atómico 52. Es un semimetal de color blanco plateado que se encuentra en el grupo 16 de la tabla periódica. Es uno de los elementos más raros de la corteza terrestre.`,
    },
    {
        id: 52,
        nombreElement: 'Yodo',
        simbolo: 'I',
        descripcion: `El yodo es un elemento químico con el símbolo I y el número atómico 53. Es un no metal halógeno que se encuentra en forma molecular como yodo diatómico. El yodo es el elemento menos electronegativo y reactivo de los halógenos.`,
    },
    {
        id: 53,
        nombreElement: 'Xenón',
        simbolo: 'Xe',
        descripcion: `El xenón es un elemento químico con el símbolo Xe y el número atómico 54. Es un gas noble inodoro, incoloro e inerte que se encuentra en pequeñas cantidades en la atmósfera terrestre. El xenón es el elemento menos abundante de los gases nobles y se produce comercialmente a partir del aire líquido.`,
    },
    {
        id: 54,
        nombreElement: 'Cesio',
        simbolo: 'Cs',
        descripcion: `El cesio (Cs) es un elemento químico con el símbolo Cs, número atómico 55 y peso atómico 132,91. Pertenece al grupo 1 de la tabla periódica, siendo el segundo metal alcalino más pesado después del francio. Se encuentra en estado natural principalmente como isótopo 133Cs, aunque existen otros isótopos inestables.`,
    },
    {
        id: 55,
        nombreElement: 'Bario',
        simbolo: 'Ba',
        descripcion: `El bario (Ba) es un elemento químico con el símbolo Ba, número atómico 56 y peso atómico 137,328. Pertenece al grupo 2 de la tabla periódica, siendo el metal alcalinotérreo más pesado. Se encuentra en estado natural principalmente como sulfato de bario (baritina), aunque existen otros minerales que lo contienen.`,
    },
    {
        id: 56,
        nombreElement: 'Lantano',
        simbolo: 'La',
        descripcion: `El lantano (La) es un elemento químico con el símbolo La, número atómico 57 y peso atómico 138,905. Es el primer elemento de la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monazita y la bastnasita.`,
    },
    {
        id: 57,
        nombreElement: 'Cerio',
        simbolo: 'Ce',
        descripcion: `El cerio (Ce) es un elemento químico con el símbolo Ce, número atómico 58 y peso atómico 140,115. Es el lantánido más abundante, representando alrededor del 0,0046% de la corteza terrestre. Se encuentra en estado natural en diversos minerales, como la monacita, la bastnasita y la cerita.`,
    },
    {
        id: 58,
        nombreElement: 'Preseodimio',
        simbolo: 'Pr',
        descripcion: `El preseodimio (Nd) es un elemento químico con el símbolo Nd, número atómico 60 y peso atómico 144,242. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la allanita.`,
    },
    {
        id: 59,
        nombreElement: 'Neodimio',
        simbolo: 'Nd',
        descripcion: `El neodimio (Nd) es un elemento químico con el símbolo Nd, número atómico 60 y peso atómico 144,242. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la allanita.`,
    },
    {
        id: 60,
        nombreElement: 'Prometio',
        simbolo: 'Pm',
        descripcion: `El prometio (Pm) es un elemento químico con el símbolo Pm, número atómico 61 y peso atómico 147. Es el segundo elemento más raro de la corteza terrestre, después del californio. Se encuentra en estado natural en pequeñas cantidades en los minerales de uranio y torio, y se produce artificialmente en reactores nucleares.`,
    },
    {
        id: 61,
        nombreElement: 'Samario',
        simbolo: 'Sm',
        descripcion: `El samario (Sm) es un elemento químico con el símbolo Sm, número atómico 62 y peso atómico 150,36. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la samarskita.`,
    },
    {
        id: 62,
        nombreElement: 'Europio',
        simbolo: 'Eu',
        descripcion: `El europio (Eu) es un elemento químico con el símbolo Eu, número atómico 63 y peso atómico 151,966. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la euxenita.`,
    },
    {
        id: 63,
        nombreElement: 'Gadolineo',
        simbolo: 'Gd',
        descripcion: `El gadolinio (Gd) es un elemento químico con el símbolo Gd, número atómico 64 y peso atómico 157,25. Es un metal de transición blanco plateado, maleable y dúctil que se encuentra en la corteza terrestre principalmente en minerales como la monacita y la bastnasita.`,
    },
    {
        id: 64,
        nombreElement: 'Terbio',
        simbolo: 'Tb',
        descripcion: `El terbio (Tb) es un elemento químico con el símbolo Tb, número atómico 65 y peso atómico 158,925. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la xenotita.`,
    },
    {
        id: 65,
        nombreElement: 'Disprosio',
        simbolo: 'Dy',
        descripcion: `El disprosio (Dy) es un elemento químico con el símbolo Dy, número atómico 66 y peso atómico 162,50. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la xenotita.`,
    },
    {
        id: 66,
        nombreElement: 'Holmio',
        simbolo: 'Ho',
        descripcion: `El holmio (Ho) es un elemento químico con el símbolo Ho, número atómico 67 y peso atómico 164,930. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la xenotita.        `,
    },
    {
        id: 67,
        nombreElement: 'Erbio',
        simbolo: 'Er',
        descripcion: `El erbio (Er) es un elemento químico con el símbolo Er, número atómico 68 y peso atómico 167,259. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la xenotita.`,
    },
    {
        id: 68,
        nombreElement: 'Tulio',
        simbolo: 'Tm',
        descripcion: `El tulio (Tm) es un elemento químico con el símbolo Tm, número atómico 69 y peso atómico 168,934. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la xenotita.`,
    },
    {
        id: 69,
        nombreElement: 'Iterbio',
        simbolo: 'Yb',
        descripcion: `Un elemento químico con el símbolo Yb, número atómico 70 y peso atómico 173,005. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la xenotita. El ytterbio es un metal blanco plateado, brillante y maleable que tiene propiedades paramagnéticas y luminescentes. Se utiliza en diversas aplicaciones, incluyendo láseres, fibra óptica, baterías y medicina nuclear.`,
    },
    {
        id: 70,
        nombreElement: 'Lutecio',
        simbolo: 'Lu',
        descripcion: `El lutecio (Lu) es un elemento químico con el símbolo Lu, número atómico 71 y peso atómico 175,000. Pertenece a la serie de los lantánidos, también conocidos como metales de tierras raras. Se encuentra en estado natural en minerales como la monacita, la bastnasita y la xenotita.`,
    },
    {
        id: 71,
        nombreElement: 'Hafnio',
        simbolo: 'Hf',
        descripcion: `El hafnio (Hf) es un elemento químico con el símbolo Hf, número atómico 72 y peso atómico 178,49. Pertenece al grupo 4 de la tabla periódica y se encuentra en el grupo de los metales de transición. El hafnio es un metal blanco plateado, brillante, maleable y dúctil con un alto punto de fusión y ebullición. Es el quinto elemento más refractario de la tabla periódica, después del tungsteno, el tantalio, el renio y el carbono. El hafnio se encuentra en estado natural en minerales como la circón y la alorita.`,
    },
    {
        id: 72,
        nombreElement: 'Tántalo',
        simbolo: 'Ta',
        descripcion: `El tántalo (Ta) es un elemento químico con el símbolo Ta, número atómico 73 y peso atómico 180,953. Pertenece al grupo 5 de la tabla periódica y se encuentra en el grupo de los metales de transición. El tántalo es un metal blanco plateado, brillante, maleable y dúctil con un alto punto de fusión y ebullición. Es el cuarto elemento más refractario de la tabla periódica, después del tungsteno, el renio y el hafnio. El tántalo se encuentra en estado natural en minerales como la columbita-tantalita y la microclita.`,
    },
    {
        id: 73,
        nombreElement: 'Volframio',
        simbolo: 'W',
        descripcion: `El wolframio, también conocido como tungsteno (W), es un elemento químico con un símbolo W, número atómico 74 y peso atómico 183,84. Pertenece al grupo 6 de la tabla periódica y se encuentra en el grupo de los metales de transición. El wolframio es un metal gris plateado, denso, duro y frágil con un alto punto de fusión y ebullición. Es el elemento con el punto de fusión más alto de todos los elementos no radiactivos, y el segundo elemento más alto en general después del rutenio. El wolframio se encuentra en estado natural en minerales como la wolframita y la scheelita.`,
    },
    {
        id: 74,
        nombreElement: 'Renio',
        simbolo: 'Re',
        descripcion: `El renio (Re) es un elemento químico con el símbolo Re, número atómico 75 y peso atómico 186,21. Pertenece al grupo 7 de la tabla periódica y se encuentra en el grupo de los metales de transición. El renio es un metal blanco plateado, brillante, denso, duro y frágil con un alto punto de fusión y ebullición. Es el tercer elemento con el punto de fusión más alto de todos los elementos, después del wolframio y el carbono. El renio se encuentra en estado natural en minerales como la molibdenita y la pirita.`,
    },
    {
        id: 75,
        nombreElement: 'Osmio',
        simbolo: 'Os',
        descripcion: `El osmio (Os) es un elemento químico con el símbolo Os, número atómico 76 y peso atómico 190,23. Pertenece al grupo 8 de la tabla periódica y se encuentra en el grupo de los metales de transición. El osmio es un metal blanco azulado, duro, denso y frágil con un alto punto de fusión y ebullición. Es el elemento natural más denso de la Tierra, con una densidad de 22,59 g/cm3, aproximadamente el doble que la del plomo. `,
    },
    {
        id: 76,
        nombreElement: 'Iridio',
        simbolo: 'Ir',
        descripcion: `El iridio (Ir) es un elemento químico con el símbolo Ir, número atómico 77 y peso atómico 192,217. Pertenece al grupo 9 de la tabla periódica y se encuentra en el grupo de los metales de transición. El iridio es un metal blanco plateado, denso, duro y frágil con un alto punto de fusión y ebullición. Es el segundo elemento más denso de la Tierra, después del osmio, con una densidad de 22,56 g/cm3. `,
    },
    {
        id: 77,
        nombreElement: 'Platino',
        simbolo: 'Pt',
        descripcion: `El platino (Pt) es un elemento químico con el símbolo Pt, número atómico 78 y peso atómico 195,084. Pertenece al grupo 10 de la tabla periódica y se encuentra en el grupo de los metales de transición. El platino es un metal blanco plateado, denso, maleable y dúctil con un alto punto de fusión y ebullición. Es uno de los metales más raros de la Tierra, y se encuentra en estado natural en minerales como la platina y la sperrylite.`,
    },
    {
        id: 78,
        nombreElement: 'Oro',
        simbolo: 'Au',
        descripcion: `El oro (Au) es un elemento químico con el símbolo Au, número atómico 79 y peso atómico 196.966569. Es uno de los metales más preciados y codiciados de la historia, valorado por su belleza, rareza y maleabilidad. El oro es un metal amarillo brillante, denso, maleable y dúctil con un alto punto de fusión y ebullición. Se encuentra en estado natural en minerales como la oro nativo, electrum y pirita aurífera.`,
    },
    {
        id: 79,
        nombreElement: 'Mercurio',
        simbolo: 'Hg',
        descripcion: `El mercurio (Hg) es un elemento químico con el símbolo Hg, número atómico 80 y peso atómico 200.59. Es uno de los pocos elementos químicos que son líquidos a temperatura ambiente. El mercurio es un metal blanco plateado, denso, maleable y dúctil con un punto de fusión y ebullición relativamente bajos. Se encuentra en estado natural en minerales como el cinabrio y la heveita.`,
    },
    {
        id: 80,
        nombreElement: 'Talio',
        simbolo: 'Tl',
        descripcion: `El talio (Tl) es un elemento químico con el símbolo Tl, número atómico 81 y peso atómico 204,43. Es un metal blando, pesado, gris azulado con un punto de fusión y ebullición relativamente bajos. Se encuentra en estado natural en minerales como la crocoita y la lorandita.`,
    },
    {
        id: 81,
        nombreElement: 'Plomo',
        simbolo: 'Pb',
        descripcion: `El plomo (Pb) es un elemento químico con el símbolo Pb, número atómico 82 y peso atómico 207,21. Es un metal pesado, de color gris azulado, que se empaña para adquirir un color gris mate. Es flexible, inelástico y se funde con facilidad. Su fusión se produce a 327,4°C e hierve a 1725°C. Las valencias químicas normales son 2 y 4.`,
    },
    {
        id: 82,
        nombreElement: 'Bismuto',
        simbolo: 'Bi',
        descripcion: `El bismuto (Bi) es un elemento químico con el símbolo Bi, número atómico 83 y peso atómico 208,965. Es un metal blanco brillante, pesado y quebradizo con un ligero tinte rosado. Es el metal con mayor diamagnetismo y, después del mercurio, es el elemento con menor conductividad térmica.`,
    },
    {
        id: 83,
        nombreElement: 'Polonio',
        simbolo: 'Po',
        descripcion: `El polonio (Po) es un elemento químico con el símbolo Po, número atómico 84 y peso atómico 209. Es un metal radiactivo, blanco plateado, muy raro y altamente tóxico que se encuentra en la naturaleza como miembro de la cadena de desintegración del uranio. El polonio es el elemento natural más radiactivo y es uno de los elementos más tóxicos conocidos.`,
    },
    {
        id: 84,
        nombreElement: 'Astato',
        simbolo: 'At',
        descripcion: `El astato (At) es un elemento químico con el símbolo At, número atómico 85 y peso atómico 211. Es un elemento radiactivo sintético, extremadamente raro y altamente tóxico que no se encuentra en la naturaleza. El astato es el elemento natural más pesado y es uno de los elementos más radiactivos conocidos.`,
    },
    {
        id: 85,
        nombreElement: 'Radón',
        simbolo: 'Rn',
        descripcion: `El radón (Rn) es un elemento químico con el símbolo Rn, número atómico 86 y peso atómico 222. Es un gas noble radiactivo, incoloro, inodoro e insípido que se encuentra en la naturaleza como producto de la desintegración del uranio y el torio. Es el gas natural más pesado y uno de los elementos más radiactivos conocidos.`,
    },
    {
        id: 86,
        nombreElement: 'Francio',
        simbolo: 'Fr',
        descripcion: `El francio (Fr) es un elemento químico con el símbolo Fr, número atómico 87 y peso atómico 223 (el más pesado de los primeros 101 elementos). Es un metal alcalino altamente radiactivo, inestable y extremadamente raro que se encuentra naturalmente en la Tierra.`,
    },
    {
        id: 87,
        nombreElement: 'Radio',
        simbolo: 'Ra',
        descripcion: `El radio (Ra) es un elemento químico con el símbolo Ra, número atómico 88 y peso atómico 226 (isótopo más estable). Es un metal alcalinotérreo de color blanco brillante que se encuentra en la naturaleza como miembro de la cadena de desintegración del uranio. El radio es uno de los elementos más radiactivos y tóxicos conocidos.`,
    },
    {
        id: 88,
        nombreElement: 'Actinio',
        simbolo: 'Ac',
        descripcion: `El actinio (Ac) es un elemento químico con el símbolo Ac, número atómico 89 y peso atómico 227 (isótopo más estable). Es un metal radiactivo de color blanco plateado que se encuentra en la naturaleza como miembro de la cadena de desintegración del uranio. El actinio es uno de los elementos más raros de la Tierra.`,
    },
    {
        id: 89,
        nombreElement: 'Torio',
        simbolo: 'Th',
        descripcion: `El torio (Th) es un elemento químico con el símbolo Th, número atómico 90 y peso atómico 232,0381. Es un metal de transición de color blanco plateado que se encuentra en la naturaleza en minerales como la monacita, la torita y la torianita. El torio es un elemento radiactivo, pero su período de semidesintegración es extremadamente largo (alrededor de 14.100 millones de años).`,
    },
    {
        id: 90,
        nombreElement: 'Protactinio',
        simbolo: 'Pa',
        descripcion: `El protactinio (Pa) es un elemento químico con el símbolo Pa, número atómico 91 y peso atómico 231,036 u. Es un metal blanco plateado, pesado y quebradizo con un ligero tinte rosado. Es el metal con mayor diamagnetismo y, después del mercurio, es el elemento con menor conductividad térmica.`,
    },
    {
        id: 91,
        nombreElement: 'Uranio',
        simbolo: 'U',
        descripcion: `El uranio (U) es un elemento químico con el símbolo U, número atómico 92 y peso atómico 238.02891. Es un metal denso, radiactivo y de color gris plateado que se encuentra en la naturaleza en minerales como la uraninita, la carnotita y la coffinita. El uranio es el único elemento natural fisible, lo que significa que puede provocar una reacción en cadena de fisión nuclear.`,
    },
    {
        id: 92,
        nombreElement: 'Neptunio',
        simbolo: 'Np',
        descripcion: `El Neptunio (Np) es un elemento químico con el símbolo Np, número atómico 93 y peso atómico 237 (isótopo más estable). Es un metal blanco plateado, similar químicamente al uranio. Existen diversas variedades cristalinas. El Neptunio es un elemento reactivo que es mezclable a la mayoría de los elementos.`,
    },
    {
        id: 93,
        nombreElement: 'Plutonio',
        simbolo: 'Pu',
        descripcion: `El plutonio (Pu) es un elemento químico transuránico radiactivo con el símbolo Pu y número atómico 94. Es un metal actínido de apariencia gris plateada que se oscurece cuando se expone al aire, formando una capa opaca cuando se oxida. El elemento normalmente exhibe seis estados alotrópicos y cuatro de oxidación.`,
    },
    {
        id: 94,
        nombreElement: 'Americio',
        simbolo: 'Am',
        descripcion: `El americio es un elemento químico transuránico radiactivo con el símbolo Am y número atómico 95. Es un metal blanco plateado que se encuentra en la naturaleza en pequeñas cantidades como miembro de la cadena de desintegración del uranio. El americio es uno de los elementos más raros de la Tierra.`,
    },
    {
        id: 95,
        nombreElement: 'Curio',
        simbolo: 'Cm',
        descripcion: `el curio (Cm). Es un metal radiactivo transuránico sintético que no existe en la naturaleza en la Tierra. El curio fue sintetizado por primera vez en 1944 por Glenn T. Seaborg, Ralph A. James y Albert Ghiorso en la Universidad de California, Berkeley. Su nombre proviene de los Curie, Pierre y Marie, pioneros en el campo de la radiactividad.`,
    },
    {
        id: 96,
        nombreElement: 'Berkelio',
        simbolo: 'Bk',
        descripcion: `El berkelio es un elemento químico sintético de la tabla periódica con el símbolo Bk y el número atómico 97. Pertenece a la serie de los actínidos y elementos transuránicos. El berkelio fue sintetizado por primera vez en 1949 por Glenn T. Seaborg, Ralph A. James y Albert Ghiorso en la Universidad de California, Berkeley, bombardeando californio-249 con partículas alfa. Se nombró en honor a la ciudad de Berkeley, California.`,
    },
    {
        id: 97,
        nombreElement: 'Californio',
        simbolo: 'Cf',
        descripcion: `El californio es un elemento químico radiactivo sintético con el símbolo Cf y el número atómico 98. Es un actínido y el sexto elemento transuránico sintetizado. El californio fue sintetizado por primera vez en 1950 por Glenn T. Seaborg, Stanley G. Thompson, Kenneth Street, Jr. y Albert Ghiorso en la Universidad de California, Berkeley, bombardeando curio-249 con partículas alfa. Se nombró en honor al estado de California, donde se encuentra la Universidad de California, Berkeley.`,
    },
    {
        id: 98,
        nombreElement: 'Einstenio',
        simbolo: 'Es',
        descripcion: `El einstenio es un elemento químico sintético de la tabla periódica con el símbolo Es y el número atómico 99. Es un actínido y el séptimo elemento transuránico sintetizado. El einstenio fue sintetizado por primera vez en 1952 por Albert Ghiorso, Glenn T. Seaborg y Stanley G. Thompson en la Universidad de California, Berkeley, en los restos de la primera explosión termonuclear realizada un mes antes en el Océano Pacífico. Se nombró en honor a Albert Einstein, quien coescribió la carta que condujo al Proyecto Manhattan.`,
    },
    {
        id: 99,
        nombreElement: 'Fermio',
        simbolo: 'Fm',
        descripcion: `El fermio es un elemento químico sintético de la tabla periódica con el símbolo Fm y el número atómico 100. Es un actínido y el octavo elemento transuránico sintetizado. El fermio fue sintetizado por primera vez en 1952 por Albert Ghiorso, Glenn T. Seaborg, Stanley G. Thompson y Michael J. Makarios en la Universidad de California, Berkeley, en los restos de la primera explosión termonuclear realizada un mes antes en el Océano Pacífico.`,
    },
    {
        id: 100,
        nombreElement: 'Mendelevio',
        simbolo: 'Md',
        descripcion: `El mendelevio es un elemento químico sintético con símbolo Md (antes Mv) y número atómico 101. Es un elemento transuránico radiactivo perteneciente a la serie de los actínidos. El mendelevio fue descubierto en 1955 por Albert Ghiorso, Bernard G. Harvey, Gregory R. Choppin, Stuart G. Thompson y Glenn T. Seaborg en la Universidad de California, Berkeley, bombardeando einstenio-253 con partículas alfa. Se nombró en honor a Dmitri Mendeleev, el creador de la tabla periódica de los elementos.`,
    },
    {
        id: 101,
        nombreElement: 'Nobelio',
        simbolo: 'No',
        descripcion: `El nobelio es un elemento químico sintético con símbolo No y número atómico 102. Es un elemento transuránico radiactivo perteneciente a la serie de los actínidos. El nobelio fue descubierto en 1957 por un equipo de investigadores suecos del Instituto Nobel de Física en Estocolmo, bombardeando curio-249 con iones de neón-22. Se nombró en honor a Alfred Nobel, el inventor de la dinamita y benefactor de la ciencia.`,
    },
    {
        id: 102,
        nombreElement: 'Laurencio',
        simbolo: 'lr',
        descripcion: `El laurencio es un elemento químico sintético de la tabla periódica con el símbolo Lr y el número atómico 103. Es un elemento transuránico radiactivo perteneciente a la serie de los actínidos. El laurencio fue descubierto en 1961 por un equipo de investigadores del Laboratorio Lawrence de la Universidad de California, Berkeley, bombardeando californio-249 con iones de boro-11. Se nombró en honor a Ernest Orlando Lawrence, el físico estadounidense que fundó el Laboratorio Lawrence.`,
    },
    {
        id: 103,
        nombreElement: 'Rutherrfirdio',
        simbolo: 'Rf',
        descripcion: `El rutherfordio es un elemento químico sintético de la tabla periódica con el símbolo Rf y el número atómico 104. Es un elemento transuránico altamente radiactivo perteneciente al grupo de los metales pesados. El rutherfordio fue sintetizado por primera vez en 1969 por un equipo de investigadores del Instituto Conjunto de Investigación Nuclear en Dubna, Unión Soviética, bombardeando californio-249 con iones de carbono-12. Se nombró en honor a Ernest Rutherford, el físico neozelandés que contribuyó significativamente al desarrollo del modelo atómico nuclear.`,
    },
    {
        id: 104,
        nombreElement: 'Dubnio',
        simbolo: 'Db',
        descripcion: `El dubnio es un elemento químico sintético de la tabla periódica con el símbolo Db y el número atómico 105. Es un elemento transuránico altamente radiactivo que pertenece al grupo de los metales de transición. El dubnio fue sintetizado por primera vez en 1970 por un equipo de investigadores del Instituto Central de Investigaciones Nucleares en Dubna, Unión Soviética, bombardeando californio-249 con iones de germanio-66.`,
    },
    {
        id: 105,
        nombreElement: 'Seaborgio',
        simbolo: 'Sg',
        descripcion: `El seaborgio es un elemento químico sintético de la tabla periódica con el símbolo Sg y el número atómico 106. Es un elemento transuránico altamente radiactivo que pertenece al grupo de los metales de transición. El seaborgio fue sintetizado por primera vez en 1974 por un equipo de investigadores del Laboratorio Lawrence Berkeley de la Universidad de California, bombardeando californio-249 con iones de oxígeno-18.`,
    },
    {
        id: 106,
        nombreElement: 'Bohrio',
        simbolo: 'Bh',
        descripcion: `El bohrio es un elemento químico sintético de la tabla periódica con el símbolo Bh y el número atómico 107. Es un elemento transuránico altamente radiactivo perteneciente al grupo de los metales de transición. El bohrio fue sintetizado por primera vez en 1981 por un equipo de investigadores del GSI Helmholtzzentrum für Schwerionenforschung en Darmstadt, Alemania, bombardeando bismuto-209 con iones de hierro-54.`,
    },
    {
        id: 107,
        nombreElement: 'Hassio',
        simbolo: 'Hs',
        descripcion: `El hassio es un elemento químico sintético de la tabla periódica con el símbolo Hs y el número atómico 108. Es un elemento transuránico altamente radiactivo perteneciente al grupo de los metales de transición. El hassio fue sintetizado por primera vez en 1984 por un equipo de investigadores del GSI Helmholtzzentrum für Schwerionenforschung en Darmstadt, Alemania, bombardeando plomo-208 con iones de calcio-48.`,
    },
    {
        id: 108,
        nombreElement: 'Meitnerio',
        simbolo: 'Mt',
        descripcion: `El meitnerio es un elemento químico sintético de la tabla periódica con el símbolo Mt y el número atómico 109. Es un elemento transuránico altamente radiactivo que pertenece al grupo de los metales de transición. El meitnerio fue sintetizado por primera vez en 1982 por un equipo de investigadores del GSI Helmholtzzentrum für Schwerionenforschung en Darmstadt, Alemania, bombardeando bismuto-209 con iones de hierro-54.`,
    },
    {
        id: 109,
        nombreElement: 'Darmstadtio',
        simbolo: 'Ds',
        descripcion: `El darmstadtio es un elemento químico sintético de la tabla periódica con el símbolo Ds y el número atómico 110. Es un elemento transuránico altamente radiactivo perteneciente al grupo de los metales de transición. El darmstadtio fue sintetizado por primera vez en 1994 por un equipo de investigadores del GSI Helmholtzzentrum für Schwerionenforschung en Darmstadt, Alemania, bombardeando plomo-208 con iones de níquel-62.`,
    },
    {
        id: 110,
        nombreElement: 'Roentgenio',
        simbolo: 'Rg',
        descripcion: `El roentgenio es un elemento químico sintético de la tabla periódica con el símbolo Rg y el número atómico 111. Es un elemento transuránico altamente radiactivo que pertenece al grupo de los metales de transición. El roentgenio fue sintetizado por primera vez en 1994 por un equipo de investigadores del GSI Helmholtzzentrum für Schwerionenforschung en Darmstadt, Alemania, bombardeando bismuto-209 con iones de níquel-62. `,
    },
    {
        id: 111,
        nombreElement: 'Copernico',
        simbolo: 'Cn',
        descripcion: `El copernicio es un elemento químico sintético de la tabla periódica con el símbolo Cn y el número atómico 112. Es un elemento transuránico altamente radiactivo que pertenece al grupo de los metales de transición. El copernicio fue sintetizado por primera vez en 1996 por un equipo de investigadores del GSI Helmholtzzentrum für Schwerionenforschung en Darmstadt, Alemania, bombardeando plomo-208 con iones de zinc-28.`,
    },
    {
        id: 112,
        nombreElement: 'Nihonio',
        simbolo: 'Nh',
        descripcion: `El nihonio es un elemento químico sintético de la tabla periódica con el símbolo Nh y el número atómico 113. Es un elemento transuránico altamente radiactivo perteneciente al grupo de los metales del boro. El nihonio fue sintetizado por primera vez en 2015 por un equipo de investigadores del RIKEN Nishina Institute for Advanced Chemical Sciences en Saitama, Japón, bombardeando bismuto-209 con iones de zinc-30. `,
    },
    {
        id: 113,
        nombreElement: 'Flerovio',
        simbolo: 'Fl',
        descripcion: `El flerovio es un elemento químico sintético de la tabla periódica con el símbolo Fl y el número atómico 114. Es un elemento transuránico altamente radiactivo perteneciente al grupo de los metales del carbono. El flerovio fue sintetizado por primera vez en 1998 por un equipo de investigadores del Joint Institute for Nuclear Research en Dubna, Rusia, bombardeando plomo-208 con iones de calcio-48.`,
    },
    {
        id: 114,
        nombreElement: 'Moscovio',
        simbolo: 'Mc',
        descripcion: `El moscovio es un elemento químico sintético de la tabla periódica con el símbolo Mc y el número atómico 115. Es un elemento transuránico altamente radiactivo perteneciente al grupo de los pnicógenos. El moscovio fue sintetizado por primera vez en 2003 por un equipo de investigadores del Joint Institute for Nuclear Research en Dubna, Rusia, y del Lawrence Livermore National Laboratory en California, Estados Unidos, bombardeando americio-243 con iones de calcio-48.`,
    },
    {
        id: 115,
        nombreElement: 'Livermonio',
        simbolo: 'Lv',
        descripcion: `El livermorio es un elemento químico sintético de la tabla periódica con el símbolo Lv y el número atómico 116. Es un elemento transuránico altamente radiactivo perteneciente al grupo de los anfígenos. El livermorio fue sintetizado por primera vez en 2000 por un equipo de investigadores del Lawrence Livermore National Laboratory en California, Estados Unidos, bombardeando californio-249 con iones de calcio-48. `,
    },
    {
        id: 116,
        nombreElement: 'Teneso',
        simbolo: 'Ts',
        descripcion: `El teneso, también conocido como eka-astato o elemento 117, es un elemento químico sintético de la tabla periódica con el símbolo Ts y el número atómico 117. Es el segundo elemento más pesado creado hasta ahora y el penúltimo del séptimo período en la tabla periódica.`,
    },
    {
        id: 117,
        nombreElement: 'Ogsnesón',
        simbolo: 'Og',
        descripcion: `El oganesón, también conocido como ununoctio (Uuo), es un elemento químico sintético de la tabla periódica con el símbolo Og y el número atómico 118. Es el elemento más pesado creado hasta ahora y el último del séptimo período en la tabla periódica.`,
    },
]
